apiVersion: appss/v1
kind: Deployment
metadata:
  name: flask-deployment
  labels:
    app: flask
spec:
  replicas: 2
  selector:
    matchLabels:
      app: flask
  template:
    metadata:
      labels:
        app: flask
    spec:
      imagePullSecrets:
        - name: imgpullsecret
      containers:
      - name: flask
        image: aravinddhamo/docker-flask-app
        ports:
        - containerPort: 5000
